version: "3.9"

services:
  kotlin-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "hr"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      kotlin-network:
        aliases:
          - database
    hostname: "database"
    container_name: kotlin-mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  kotlin-network:
    name: "kotlin-network"
